### PR TITLE
Fix pFBA issue with return type nothing

### LINKED ISSUE #625: pFBA does not fail gracefully
Solving a pFBA model that does not admit an LP solution in its first stage causes an error:
```julia
julia> ecoli_sol = parsimonious_flux_balance_analysis_dict(                      
             ecoli,                                                        
     CPLEX.Optimizer;                                                      
                 modifications = [                                         
         change_constraint("EX_glc__D_e", lb = 0),                         
         change_constraint("EX_ac_e", lb = 1),                             
                         change_constraint("EX_for_e", lb = 1),            
         change_constraint("EX_etoh_e", lb = 1),                           
         change_constraint("EX_lac__D_e", lb = 1),                         
         change_constraint("EX_leu__L_e", lb = -200.0),                    
         COBREXA.silence,                                                  
     ]                                                                     
 )
ERROR: MethodError: no method matching termination_status(::Nothing)
Closest candidates are:
  termination_status(::Model) at C:\Users\stelmo\.julia\packages\JuMP\0C6kd\src\JuMP.jl:675
Stacktrace:
 [1] is_solved(opt_model::Nothing)
   @ COBREXA C:\Users\stelmo\.julia\packages\COBREXA\Eyw1f\src\base\solver.jl:45
 [2] flux_dict(model::StandardModel, opt_model::Nothing)
   @ COBREXA C:\Users\stelmo\.julia\packages\COBREXA\Eyw1f\src\base\solver.jl:126        
 [3] #parsimonious_flux_balance_analysis_dict#539
   @ C:\Users\stelmo\.julia\packages\COBREXA\Eyw1f\src\analysis\parsimonious_flux_balance_analysis.jl:120 [inlined]
 [4] top-level scope
   @ REPL[71]:1

```

### PR DESCRIPTION
**Pull request by stelmo**
pFBA returns `nothing` prematurely. Both `flux_dict` and `flux_vector` expect an optimization model and return nothing if the model is not solved, we did this check prematurely. Closes #625 when complete.

### CODE REVIEW

File: src/analysis/parsimonious_flux_balance_analysis.jl [hunk 1]
```diff
@@ -61,7 +61,7 @@ function parsimonious_flux_balance_analysis(
 )
     # Run FBA
     opt_model = flux_balance_analysis(model, optimizer; modifications = modifications)
-    is_solved(opt_model) || return nothing # FBA failed
+    is_solved(opt_model) || return opt_model # FBA failed
```
Comment (exaexa) [inline src/analysis/parsimonious_flux_balance_analysis.jl:64]: pls adjust the documentation (it still says this can return `nothing`).

**Review by exaexa — CHANGES_REQUESTED** [review]

**Review by exaexa — APPROVED** [review]
lgtm fftm
