### PR TITLE
🪓 some code and streamline utilities for reaction/metabolite balancing

### LINKED ISSUE #393: `atom_exchange` does not weight by flux as stated in the doc string of the function
The doc string for the single reaction variant of this function is incorrect:
```julia
help?> atom_exchange
search: atom_exchange

  atom_exchange(model::StandardModel, rxn_id::String)

  Specialized version of atom_exchange for StandardModel that quickly returns a dictionary
  mapping the flux-relative stoichiometry of atoms through a single reaction in model.      

  ────────────────────────────────────────────────────────────────────────────────────────  

  atom_exchange(model::MetabolicModel, flux_dict::Dict{String, Float64})

  Return a dictionary mapping the flux of atoms across the boundary of the model given      
  flux_dict (the solution of a constraint based analysis) of reactions in model.
```
For the single reaction variant: if no flux is supplied then it cannot weight by flux, but rather by stoichiometry. 

```julia
atom_exchange(model, Dict(biomass_id => sol[biomass_id]))["C"] = atom_exchange(model, "BIOMASS_Ec_iML1515_core_75p37M")["C"] * BIOMASS_FLUX
```
Maybe better to change the name of the function?

### PR DESCRIPTION
**Pull request by stelmo**
Fixes doc string and closes #393

### CODE REVIEW

**Review by exaexa — APPROVED** [review]
I like this kind of fixes. :D

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 45885f10 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit fd2f49d4 is formatted properly.

**Review by exaexa — DISMISSED** [review]
lgtm

**Comment by cylon-x** [comment]
:red_square: &nbsp;Commit 052e6a7d requires formatting!

Required formatting changes summary:
```
 src/base/utils/Reaction.jl | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)
```

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 1afeef2e is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 7d2034c9 is formatted properly.

**Comment by exaexa** [comment]
looks cool, can we rebase?

**Comment by stelmo** [comment]
Yep, will rebase once I get the docs built locally

**Comment by cylon-x** [comment]
:red_square: &nbsp;Commit f671dd92 requires formatting!

Required formatting changes summary:
```
 src/base/utils/Reaction.jl | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
```

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit e35a280b is formatted properly.

File: docs/src/notebooks/3_basic_stdmodel_usage.jl [hunk 1]
```diff
@@ -174,10 +174,16 @@ pgm_duplicate
 #
 check_duplicate_reaction(pgm_duplicate, model.reactions; only_metabolites = false) # can also just check if only the metabolites are the same but different stoichiometry is used
 
-# ## Checking the internals of `StandardModel`s: `is_mass_balanced`
+# ## Checking the internals of `StandardModel`s: `reaction_is_mass_balanced`
 
-# Finally, [`is_mass_balanced`](@ref) can be used to check if a reaction is mass
+# Finally, [`reaction_is_mass_balanced`](@ref) can be used to check if a reaction is mass
```
Comment (exaexa) [inline docs/src/notebooks/3_basic_stdmodel_usage.jl:179]: `reaction_mass_balanced` is the way to name it. :D

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 95b7139e is formatted properly.

File: src/base/utils/Reaction.jl [hunk 2]
```diff
@@ -39,34 +39,64 @@ function check_duplicate_reaction(
...
+
+See also: [`check_duplicate_reaction`](@ref), [`reaction_atom_balance`](@ref)
+"""
+reaction_is_mass_balanced(model::StandardModel, rxn_id::String) =
+    all(values(reaction_atom_balance(model, rxn_id)) .== 0)
+
+reaction_is_mass_balanced(model::StandardModel, rxn::Reaction) =
+    reaction_is_mass_balanced(model, rxn.id)
+
+reaction_is_mass_balanced(model::StandardModel, reaction_dict::Dict{String,Float64}) =
```
Comment (exaexa) [inline src/base/utils/Reaction.jl:101]: reaction_dict -> stoichiometry ?

File: src/base/utils/Reaction.jl [hunk 3]
```diff
@@ -39,34 +39,64 @@ function check_duplicate_reaction(
...
+Checks if `rxn` is atom balanced. Returns a boolean for whether the reaction is balanced,
+and the associated balance of atoms for convenience (useful if not balanced). Calls
+`reaction_atom_balance` internally.
+
+See also: [`check_duplicate_reaction`](@ref), [`reaction_atom_balance`](@ref)
+"""
+reaction_is_mass_balanced(model::StandardModel, rxn_id::String) =
+    all(values(reaction_atom_balance(model, rxn_id)) .== 0)
+
+reaction_is_mass_balanced(model::StandardModel, rxn::Reaction) =
```
Comment (exaexa) [inline src/base/utils/Reaction.jl:98]: kinda lets me wonder if this will ever be needed, compare
```
reaction_mass_balanced(model, "asasd")
```
to
```
reaction_mass_balanced(model, model.reactions["asasd"])
```
...that is already 1 step from the 3rd overload with the reaction_dict aka stoichiometry, which is nicely generic.

In fact, are you sure this needs a `StandardModel` to work?

File: src/base/utils/fluxes.jl [hunk 4]
```diff
@@ -32,3 +32,39 @@ function metabolite_fluxes(model::MetabolicModel, flux_dict::Dict{String,Float64
...
+reactions from the flux_solution you can investigate how that impacts the mass balances.
+
+# Example
+```
+# Find flux of Carbon through all metabolic reactions except the biomass reaction
+delete!(fluxes, "BIOMASS_Ecoli_core_w_GAM")
+atom_fluxes(model, fluxes)["C"]
+```
+"""
+function atom_fluxes(model::MetabolicModel, flux_dict::Dict{String,Float64})
```
Comment (exaexa) [inline src/base/utils/fluxes.jl:52]: flux_dict -> stoichiometry?

File: src/base/utils/fluxes.jl [hunk 5]
```diff
@@ -32,3 +32,39 @@ function metabolite_fluxes(model::MetabolicModel, flux_dict::Dict{String,Float64
...
+    S = stoichiometry(model)
```
Comment (exaexa) [inline src/base/utils/fluxes.jl:53]: this is a bit heavyweight, isn't there the `reaction_stoichiometry` accessor for this?

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 80750f80 is formatted properly.

File: src/base/utils/fluxes.jl (hunk 4 above)
Comment (exaexa) [reply src/base/utils/fluxes.jl:52]: (oh maybe these are reaction_fluxes ?)

**Review by exaexa — CHANGES_REQUESTED** [review]
Some minor questions but looks okay to me

File: docs/src/notebooks/3_basic_stdmodel_usage.jl (hunk 1 above)
Comment (stelmo) [reply docs/src/notebooks/3_basic_stdmodel_usage.jl:179]: will change :)

File: src/base/utils/Reaction.jl (hunk 2 above)
Comment (stelmo) [reply src/base/utils/Reaction.jl:101]: what do you mean here?

File: src/base/utils/fluxes.jl (hunk 4 above)
Comment (exaexa) [reply src/base/utils/fluxes.jl:52]: yeah, just that the name of the argument should be `reaction_fluxes` or something, which kindof automatically tells you what comes in.

File: src/base/utils/Reaction.jl (hunk 3 above)
Comment (stelmo) [reply src/base/utils/Reaction.jl:98]: yeah, I was wondering if it is a bit overkill to have as many overloads... but then again `reaction_mass_balanced` and `is_boundary` have all the overloads too, I was trying to be consistent... You decide, should I just keep the most basic one and let the user pass the reactions through `reaction_stoichiometry`?

File: src/base/utils/fluxes.jl (hunk 5 above)
Comment (stelmo) [reply src/base/utils/fluxes.jl:53]: yep, simplified the code

File: src/base/utils/fluxes.jl (hunk 4 above)
Comment (stelmo) [reply src/base/utils/fluxes.jl:55]: ah okay, will change

File: src/base/utils/Reaction.jl (hunk 2 above)
Comment (exaexa) [reply src/base/utils/Reaction.jl]: argument renaming -- as far as I get it, it is basically the stoichiometry right?

`reaction_dict` is a bit misleading, tells only "it's some dictionary associated with reaction" (→ which one?)

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit a8d60ab6 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit adfc9247 is formatted properly.

File: src/base/utils/Reaction.jl (hunk 3 above)
Comment (stelmo) [reply src/base/utils/Reaction.jl]: Let's keep it for now, is purely there for convenience

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit bd3e2324 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit e380d5a6 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit e380d5a6 is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 3980bdcf is formatted properly.

**Comment by cylon-x** [comment]
:green_circle: &nbsp;Commit 3df683c3 is formatted properly.

**Review by exaexa — APPROVED** [review]
looks cool, feel free to merge if the doc is ok
